//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCuestionario
    {
        public AsignacionCuestionario()
        {
            this.Respuestas = new HashSet<Respuestas>();
            this.Tablainter2 = new HashSet<Tablainter2>();
        }
    
        public int IDAsignacionCuestionario { get; set; }
        public string Fechafinalizado { get; set; }
        public Nullable<int> Idcuestionario { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<int> Idpersona { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public string FechaAsignacion { get; set; }
    
        public virtual Cuestionarios Cuestionarios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        public virtual ICollection<Tablainter2> Tablainter2 { get; set; }
    }
}
