//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autores
    {
        public Autores()
        {
            this.Tablainter1 = new HashSet<Tablainter1>();
        }
    
        public int IDautor { get; set; }
        public string PrimerNombre { get; set; }
        public string ApellidoPrimero { get; set; }
        public string Cedula { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Eliminautor { get; set; }
        public string Filial { get; set; }
        public string ApellidoSegundo { get; set; }
        public string SegundoNombre { get; set; }
    
        public virtual ICollection<Tablainter1> Tablainter1 { get; set; }
    }
}
