//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras
    {
        public Carreras()
        {
            this.Libros = new HashSet<Libros>();
        }
    
        public int IDcarrera { get; set; }
        public string Carrera { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual ICollection<Libros> Libros { get; set; }
    }
}
