//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int IDcomentario { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Eliminacoment { get; set; }
        public Nullable<int> Idproceso { get; set; }
        public Nullable<int> Idusuario { get; set; }
        public string Fecha { get; set; }
    
        public virtual Procesos Procesos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
