//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosTiposproceso
    {
        public EstadosTiposproceso()
        {
            this.MensajesTiposproceso = new HashSet<MensajesTiposproceso>();
        }
    
        public int IDEstadosTiposproceso { get; set; }
        public int IdentificadorEstados { get; set; }
        public string DetalleEstados { get; set; }
        public Nullable<bool> EliminadoEstados { get; set; }
        public Nullable<int> Idtipoproceso { get; set; }
        public Nullable<bool> VRequerimientosAutor { get; set; }
        public Nullable<bool> VEnviarProcesoRevision { get; set; }
        public Nullable<bool> VEnviarRevisionReversado { get; set; }
        public Nullable<bool> VRequerimientosAdmin { get; set; }
        public Nullable<bool> VEnviarResultados { get; set; }
        public Nullable<bool> VIniciarSiguienteProceso { get; set; }
        public Nullable<bool> VAsignarEvaluadores { get; set; }
        public Nullable<bool> VEnviarEvaluacionPares { get; set; }
        public Nullable<bool> VPublicacionLibro { get; set; }
    
        public virtual Tiposproceso Tiposproceso { get; set; }
        public virtual ICollection<MensajesTiposproceso> MensajesTiposproceso { get; set; }
    }
}
