//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formatos
    {
        public int IDformato { get; set; }
        public string Archivo { get; set; }
        public string Detallearchivo { get; set; }
        public Nullable<int> Idtipoformato { get; set; }
        public Nullable<bool> Eliminaform { get; set; }
        public string DescripcionFormato { get; set; }
    
        public virtual Tipoformatos Tipoformatos { get; set; }
    }
}
