//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionEditorial
    {
        public int IDinformacion { get; set; }
        public string TituloInformacion { get; set; }
        public string EnunciadoInformacion { get; set; }
        public string ImagenInfo { get; set; }
        public string UrlInfo { get; set; }
        public Nullable<bool> EliminadoInfo { get; set; }
        public Nullable<int> Pagina { get; set; }
    }
}
