//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.Procesos = new HashSet<Procesos>();
            this.Tablainter1 = new HashSet<Tablainter1>();
            this.VistasLibros = new HashSet<VistasLibros>();
        }
    
        public int IDlibro { get; set; }
        public string Titulo { get; set; }
        public string CodigoISBN { get; set; }
        public string Fechapublica { get; set; }
        public string Editorial { get; set; }
        public string Libro { get; set; }
        public string Portada { get; set; }
        public Nullable<bool> Eliminalibros { get; set; }
        public Nullable<int> Idcategoria { get; set; }
        public Nullable<int> Idusuario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string ProcesoL { get; set; }
        public Nullable<int> ProgresoL { get; set; }
        public string EstadoL { get; set; }
        public Nullable<int> IdprocesoL { get; set; }
        public string UrlAcceso { get; set; }
        public Nullable<bool> Archivado { get; set; }
        public string Creado { get; set; }
        public string Actualizado { get; set; }
        public Nullable<bool> Aceptado { get; set; }
        public Nullable<int> Idcarrera { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<bool> Externo { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Procesos> Procesos { get; set; }
        public virtual ICollection<Tablainter1> Tablainter1 { get; set; }
        public virtual ICollection<VistasLibros> VistasLibros { get; set; }
    }
}
