//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public Noticias()
        {
            this.Imagenes = new HashSet<Imagenes>();
        }
    
        public int IDNoticia { get; set; }
        public string DetalleNoticia { get; set; }
        public string DescripcionNoticia { get; set; }
        public Nullable<bool> EliminaNoticia { get; set; }
        public string ImagenNoticia { get; set; }
        public string Titulonoticia { get; set; }
        public string Fechapublica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> Fechapublicacion { get; set; }
        public string Urlacceso { get; set; }
    
        public virtual ICollection<Imagenes> Imagenes { get; set; }
    }
}
