//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int IDnotificacion { get; set; }
        public string Notificacion1 { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string UrlNotificacion { get; set; }
        public string Visible { get; set; }
        public Nullable<int> Idusuario { get; set; }
        public Nullable<int> Idtiponotificacion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public string Fechanotifi { get; set; }
        public string DetalleNotificacion { get; set; }
        public Nullable<bool> General { get; set; }
        public Nullable<bool> Publicado { get; set; }
    
        public virtual TipoNotificacion TipoNotificacion { get; set; }
    }
}
