//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesos
    {
        public Procesos()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Documentos = new HashSet<Documentos>();
            this.ObservacionesProceso = new HashSet<ObservacionesProceso>();
            this.Tablainter2 = new HashSet<Tablainter2>();
        }
    
        public int IDproceso { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Eliminaproceso { get; set; }
        public Nullable<int> Idlibro { get; set; }
        public Nullable<int> Idtipoproceso { get; set; }
        public string InicioFecha { get; set; }
        public string ActualizadoFecha { get; set; }
        public Nullable<int> Idprocanterior { get; set; }
        public Nullable<int> Opresultado { get; set; }
        public Nullable<int> IdentificaEstado { get; set; }
    
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual ICollection<Documentos> Documentos { get; set; }
        public virtual Libros Libros { get; set; }
        public virtual ICollection<ObservacionesProceso> ObservacionesProceso { get; set; }
        public virtual Tiposproceso Tiposproceso { get; set; }
        public virtual ICollection<Tablainter2> Tablainter2 { get; set; }
    }
}
