//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequerimientosProcesos
    {
        public RequerimientosProcesos()
        {
            this.RespuestaRequerimiento = new HashSet<RespuestaRequerimiento>();
        }
    
        public int IDrequerimiento { get; set; }
        public string Detallerequerimiento { get; set; }
        public Nullable<int> Idtipoproceso { get; set; }
        public Nullable<bool> Eliminarequerimiento { get; set; }
        public string Descripcionrequerimiento { get; set; }
        public string Emisor { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> Idtipodato { get; set; }
        public Nullable<bool> Visibleautor { get; set; }
        public Nullable<bool> Visibleevaluador { get; set; }
        public Nullable<bool> Visibleadmin { get; set; }
        public Nullable<bool> Obligatorio { get; set; }
        public Nullable<bool> ResultadoProceso { get; set; }
    
        public virtual Tiposproceso Tiposproceso { get; set; }
        public virtual TipodeDato TipodeDato { get; set; }
        public virtual ICollection<RespuestaRequerimiento> RespuestaRequerimiento { get; set; }
    }
}
