//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaRequerimiento
    {
        public int IDrespuestaRequerimiento { get; set; }
        public string DetalleResp { get; set; }
        public Nullable<int> ProgresoResp { get; set; }
        public Nullable<int> Idrequerimiento { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual RequerimientosProcesos RequerimientosProcesos { get; set; }
    }
}
