//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlidersEditorial
    {
        public int IDSlider { get; set; }
        public string Titulo { get; set; }
        public string Enunciado { get; set; }
        public string ImagenSlider { get; set; }
        public string Urlslider { get; set; }
        public Nullable<bool> EliminadoSlider { get; set; }
    }
}
