//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablainter2
    {
        public int IDtablainter2 { get; set; }
        public Nullable<int> Idevaluador { get; set; }
        public Nullable<bool> EliminadoT2 { get; set; }
        public Nullable<int> Idproceso { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdasignacionEvaluacion { get; set; }
        public Nullable<int> NumEvaluador { get; set; }
    
        public virtual AsignacionCuestionario AsignacionCuestionario { get; set; }
        public virtual Procesos Procesos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
