//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipodeDato
    {
        public TipodeDato()
        {
            this.PreguntaAbierta = new HashSet<PreguntaAbierta>();
            this.RequerimientosProcesos = new HashSet<RequerimientosProcesos>();
        }
    
        public int IDtipodato { get; set; }
        public Nullable<int> Identificador { get; set; }
        public string TipoHtml { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual ICollection<PreguntaAbierta> PreguntaAbierta { get; set; }
        public virtual ICollection<RequerimientosProcesos> RequerimientosProcesos { get; set; }
    }
}
