//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiposusuarios
    {
        public Tiposusuarios()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IDtipousuario { get; set; }
        public string Detalleusuario { get; set; }
        public Nullable<bool> Eliminatipouser { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
