//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNotificacion
    {
        public TipoNotificacion()
        {
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public int IDtipoNotificacion { get; set; }
        public string DetalleTipoNotificacion { get; set; }
        public string Icono { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual ICollection<Notificacion> Notificacion { get; set; }
    }
}
