//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiposproceso
    {
        public Tiposproceso()
        {
            this.EstadosTiposproceso = new HashSet<EstadosTiposproceso>();
            this.Procesos = new HashSet<Procesos>();
            this.RequerimientosProcesos = new HashSet<RequerimientosProcesos>();
        }
    
        public int IDtiposprocesos { get; set; }
        public Nullable<int> Numeroprocesos { get; set; }
        public string Detalletipospro { get; set; }
        public Nullable<int> Progreso { get; set; }
        public Nullable<bool> Eliminatipospro { get; set; }
        public string Duracionproceso { get; set; }
        public Nullable<int> Identificador { get; set; }
        public string Descripciontipoproceso { get; set; }
    
        public virtual ICollection<EstadosTiposproceso> EstadosTiposproceso { get; set; }
        public virtual ICollection<Procesos> Procesos { get; set; }
        public virtual ICollection<RequerimientosProcesos> RequerimientosProcesos { get; set; }
    }
}
