//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.AsignacionCuestionario = new HashSet<AsignacionCuestionario>();
            this.Comentarios = new HashSet<Comentarios>();
            this.Libros = new HashSet<Libros>();
            this.Respuestas = new HashSet<Respuestas>();
            this.Tablainter2 = new HashSet<Tablainter2>();
        }
    
        public int IDusuario { get; set; }
        public string PrimerNombre { get; set; }
        public string ApellidoPrimero { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Idtipousuario { get; set; }
        public Nullable<bool> Eliminauser { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Filial { get; set; }
        public string Token_recovery { get; set; }
        public string Cedula { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> Librosproceso { get; set; }
        public Nullable<int> Librosfinalizados { get; set; }
        public string ApellidoSegundo { get; set; }
        public string SegundoNombre { get; set; }
    
        public virtual ICollection<AsignacionCuestionario> AsignacionCuestionario { get; set; }
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual ICollection<Libros> Libros { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        public virtual ICollection<Tablainter2> Tablainter2 { get; set; }
        public virtual Tiposusuarios Tiposusuarios { get; set; }
    }
}
