//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistasLibros
    {
        public int IDvistas { get; set; }
        public string IPvistas { get; set; }
        public Nullable<System.DateTime> Fechavistas { get; set; }
        public Nullable<int> Idlibro { get; set; }
    
        public virtual Libros Libros { get; set; }
    }
}
